### ISSUE TITLE
Reverse order of "\r\n" in the validate method

### ISSUE THREAD

**Issue by realyze** [Nitron/django-cas-provider#1]
I believe that you have reversed the order of CRLF characters in the "validate" method. It should be "\r\n". 
It makes e.g. Hudson's (pardon, I mean Jenkins's :-) ) CAS plugin ignore the username.

**Comment by Nitron** [comment]
Whoa, how did that happen?

I'll take care of this when I have a break between classes (in a few hours). Thanks for the heads up!

**Comment by Nitron** [comment]
I just pushed the change. Does it work with Hudson now? I'll hold off on closing the issue until I get confirmation.

**Comment by realyze** [comment]
Bug fixed. :-) 
And kudos on your app, it's exactly what I was looking for.
