### ISSUE TITLE
Does not use LOGIN_REDIRECT_URL setting.

### ISSUE THREAD

**Issue by AndreLouisCaron** [Nitron/django-cas-provider#3]
I was quite surprised to see that my `LOGIN_REDIRECT_URL` is consistently ignored and I'm always redirected to `/account/` after login.  It seems that the `cas_provider.views.login` view uses an extra parameter with the URL to redirect to.

This should be changed to use the `LOGIN_REDIRECT_URL` setting for two reasons.  First, the replacement login view should behave as much as possible like the one in `django.contrib.auth`.  Second, I cannot use the `include(cas_provider.urls)` shortcut in my project's `urls.py` if I plan to use the `success_redirect` parameter.

**Comment by Nitron** [comment]
I think zuber already closed the pull request on this, so I'm closing this ticket. If I'm wrong, feel free to correct me.
